### ISSUE TITLE
How to Use it? 

### ISSUE THREAD

**Issue by Jst-Tan** [A7abhilash/google-classroom-clone#1]
Hi! May I use this source code and how to host it on GitHub Pages?

**Comment by A7abhilash** [comment]
@Jst-Tan Heyyy! You can definitely use the source code. 

1. Forking this repository into your account. After forking, clone the project to get a copy to your local PC.
2. Create a `firebaseConfig.js` file and add the necessary details from firebase as follow:
```js
export const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
};
```
3. Hit ```npm i``` and ```npm start```
4. Do the same steps as for [Google drive clone](https://github.com/A7abhilash/google-drive-clone)

**Comment by Jst-Tan** [comment]
Ok thanks! So I needed to clone the source code and create a firebaseConfig.js file and then use the terminal? 

May I know which folder is used to host the site through??

**Comment by A7abhilash** [comment]
@Jst-Tan Yeah create `firebaseConfig.js` in /src directory itself in both the projects...
You shall have to host both the projects.
